I'm sorry, but an uncaught exception occurred.

While running game code:
  File "game/script.rpy", line 325, in script
    if tasks >= 3:
  File "game/script.rpy", line 325, in <module>
    if tasks >= 3:
NameError: name 'tasks' is not defined

-- Full Traceback ------------------------------------------------------------

Full traceback:
  File "game/script.rpy", line 325, in script
    if tasks >= 3:
  File "C:\Users\hnes1\Downloads\renpy-8.3.3-sdk\renpy\ast.py", line 1843, in execute
    if renpy.python.py_eval(condition):
  File "C:\Users\hnes1\Downloads\renpy-8.3.3-sdk\renpy\python.py", line 1209, in py_eval
    return py_eval_bytecode(code, globals, locals)
  File "C:\Users\hnes1\Downloads\renpy-8.3.3-sdk\renpy\python.py", line 1202, in py_eval_bytecode
    return eval(bytecode, globals, locals)
  File "game/script.rpy", line 325, in <module>
    if tasks >= 3:
NameError: name 'tasks' is not defined

Windows-10-10.0.22631 AMD64
Ren'Py 8.3.3.24111502
Бáба-Ягá 1.0
Tue Dec 17 10:28:12 2024
